apiVersion: v1
kind: Service
metadata:
  name: backstage
  labels:
    app: backstage
spec:
  selector:
    app: backstage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: NodePort